### ISSUE TITLE
[!] (plugin Typescript) TypeError: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by eyab** [codemirror/lang-example#5]
When I try to ` npm run prepare` I am getting the following error. I tried even without changing anything from the code but still, without any changes, I am getting the following. Any help will be appreciated. 

```

src/index.ts → dist/index.cjs, ./dist...
[!] (plugin Typescript) TypeError: Cannot read properties of undefined (reading 'text')
TypeError: Cannot read properties of undefined (reading 'text')
    at getExportedSymbolFromExportSpecifier (/Users/eya/Downloads/lang-example-main-copy/node_modules/rollup-plugin-ts/dist/cjs/index.js:2082:41)
    at createExportSpecifierFromNameAndModifiers (/Users/eya/Downloads/lang-example-main-copy/node_modules/rollup-plugin-ts/dist/cjs/index.js:2103:29)
    at visitVariableStatement$5 (/Users/eya/Downloads/lang-example-main-copy/node_modules/rollup-plugin-ts/dist/cjs/index.js:2434:36)
    at visitNode$c (/Users/eya/Downloads/lang-example-main-copy/node_modules/rollup-plugin-ts/dist/cjs/index.js:2537:16)
    at /Users/eya/Downloads/lang-example-main-copy/node_modules/rollup-plugin-ts/dist/cjs/index.js:2554:13
    at visitNodes (/Users/eya/Downloads/lang-example-main-copy/node_modules/typescript/lib/typescript.js:29880:30)
    at Object.forEachChild (/Users/eya/Downloads/lang-example-main-copy/node_modules/typescript/lib/typescript.js:30122:24)
    at Object.childContinuation (/Users/eya/Downloads/lang-example-main-copy/node_modules/rollup-plugin-ts/dist/cjs/index.js:2553:52)
    at visitModuleDeclaration$8 (/Users/eya/Downloads/lang-example-main-copy/node_modules/rollup-plugin-ts/dist/cjs/index.js:2455:28)
    at visitNode$c (/Users/eya/Downloads/lang-example-main-copy/node_modules/rollup-plugin-ts/dist/cjs/index.js:2534:16)
```

**Comment by marijnh** [comment]
Seems rollup-plugin-ts pushed a broken or incompatible update. I've upgraded it to version 2.0 in caaf2ae, which seems to resolve the problem.
